// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDF6anWDOS_ogSeaxQoYVweL9C10UeGUc',
    appId: '1:1080316780211:web:1f565c613c6f0d7dfc9ac6',
    messagingSenderId: '1080316780211',
    projectId: 'pushnotification-9a082',
    authDomain: 'pushnotification-9a082.firebaseapp.com',
    storageBucket: 'pushnotification-9a082.firebasestorage.app',
    measurementId: 'G-KRHH1WXTBB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXOaVa0W0KrPvCahKS4esNAZk1TGXCzgk',
    appId: '1:1080316780211:android:1fd72cfb6c5846e6fc9ac6',
    messagingSenderId: '1080316780211',
    projectId: 'pushnotification-9a082',
    storageBucket: 'pushnotification-9a082.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyVToY2RZPzF2v-GmoiZlDpWzwazWcUr0',
    appId: '1:1080316780211:ios:5f4f26635031d85bfc9ac6',
    messagingSenderId: '1080316780211',
    projectId: 'pushnotification-9a082',
    storageBucket: 'pushnotification-9a082.firebasestorage.app',
    iosBundleId: 'com.example.pushNotification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyVToY2RZPzF2v-GmoiZlDpWzwazWcUr0',
    appId: '1:1080316780211:ios:5f4f26635031d85bfc9ac6',
    messagingSenderId: '1080316780211',
    projectId: 'pushnotification-9a082',
    storageBucket: 'pushnotification-9a082.firebasestorage.app',
    iosBundleId: 'com.example.pushNotification',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDF6anWDOS_ogSeaxQoYVweL9C10UeGUc',
    appId: '1:1080316780211:web:5af4325feadd24e2fc9ac6',
    messagingSenderId: '1080316780211',
    projectId: 'pushnotification-9a082',
    authDomain: 'pushnotification-9a082.firebaseapp.com',
    storageBucket: 'pushnotification-9a082.firebasestorage.app',
    measurementId: 'G-8Q116D5NVL',
  );
}
